# Generated by Django 3.1.7 on 2021-03-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название комнаты')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название колонки')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_column', to='tasks.room', verbose_name='Название комнаты')),
            ],
            options={
                'verbose_name': 'Колонки на комнате',
                'verbose_name_plural': 'Колонки на комнатвх',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=512, verbose_name='Текст')),
                ('room_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.roomcolumn', verbose_name='Колонка')),
                ('user_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='RoomPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_permission', to='tasks.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Разрешения на комнату',
                'verbose_name_plural': 'Разрешения на комнаты',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
