# Generated by Django 3.1.7 on 2021-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210310_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['room_column', 'order'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Порядок'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['room_column', 'order'], name='tasks_task_room_co_329c70_idx'),
        ),
    ]
