# Generated by Django 3.1.7 on 2021-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210316_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.FloatField(null=True, verbose_name='Порядок'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('room_column', 'order')},
        ),
    ]
